### ISSUE TITLE
Lock beard deploys and investigate possibly related sickness across the team

### ISSUE THREAD

**Issue by hasan-dot** [hasan-dot/hasan-dot#2]
@izuzak reported in slack:

> I'm not a rocket surgeon, but my unprofessional observation is that these problems started happening after you shaved your beard. Then @hasan-dot shaved his beard a few days ago and he got ill yesterday. :tinfoilhat:

**Comment by bottsepp** [comment]
metric/signal datapoint: haven't shaved my beard off for 8years now, generally low sickness levels but not zero 🧔‍♂️

**Comment by hasan-dot** [comment]
/
